print  ("Olá mundo!")
print ("Brasil Ganhou!")
print ("Meu Nome é Carolina Alves da Silva")
print ("Eu tenho 35 anos e moro em Porto Alegre")
print("   (\\_/)")
print("   ( •_•)")
print("   / >🍃")
input("Digite seu nome aqui")
print("Coelho comendo 🍃")
